[WIP] Add AppImageUpdate support to Linux AppImage releases
pencil2d/pencil pull request #1680
Opened 2021-11-20 02:35 UTC by scribblemaniac

This adds the update information to the appimage through linuxdeploy's `updateinformation` parameter when building from the release branch. This should cause it to generate a .zsync file which is zipped together with the AppImage for release uploads. In future releases this file will be included with the other release assets on Github.

This is marked WIP because I do not have the ability to full test this (my fork's CI environment is not set up to support uploads). I need someone to test that it uploads the files correctly still for the Linux builds, particularly on a release branch. I have tested enough to tell that it will work up until the upload step at least on both release and non-release branches. If someone could share the uploaded or link the release zip here, that would also be helpful as someone needs to verify that the update information is correctly embedded in the appimage and I should be able to do that if I get a copy of the appimage.

2021-11-20 12:20 UTC, J5lx commented
Pretty cool! I’ll take a look at this later today

2021-11-21 05:33 UTC, J5lx requested changes
Looks good overall. I noticed one small issue in the zsync metadata which still contained the original filename (from before the rename), but I fixed that over here: scribblemaniac#8 I also adjusted the upload action to upload both files individually instead of zipped. Once that is merged (the zsync fix to be precise) this PR should be good to go as far as I’m concerned. Well done!

P.S. Here are the links to [the AppImage](https://drive.google.com/file/d/1fgweIaQzZIydEA-jSWmdgK9MNkcxFmUa/view?usp=sharing) and [the zsync file](https://drive.google.com/file/d/1BHwxO8TUXvD8t33eRNuhsZfWlFUj6nws/view?usp=sharing).

2021-11-21 06:17 UTC, scribblemaniac commented
The appimage seems to have the correct data as far as I can tell. Thanks for testing and the fixes.

2022-01-11 22:34 UTC, J5lx approved these changes
It’s been far too long. Since all issues have been addressed, I reckon it’s time to merge this. I’ll also update the release checklist as discussed on Discord.

2022-01-11 22:38 UTC, J5lx commented
GitHub apparently didn’t recognize the merge again, so I’m closing this manually. The PR has been merged, though.

2022-01-11 22:38 UTC, closed without merging