Implement preferences for inverting drag and scroll zoom
pencil2d/pencil pull request #1780
Opened 2023-08-04 02:07 UTC by HeCorr

Closes #462, closes #1779.

This PR adds two preference options for inverting the zoom direction when scrolling the mouse wheel and Ctrl + Middle/Right-click dragging.

Here's two videos demonstrating them in action:

Scroll Wheel:
https://github.com/pencil2d/pencil/assets/75134774/f7849fa9-53fb-4959-9e3e-87fa0fb8f617

Hand Tool:
https://github.com/pencil2d/pencil/assets/75134774/a6312617-8c0f-465a-89b9-dd73f892fdf5

2023-08-04 06:19 UTC, MrStevns requested changes
Hi Henrique

Thanks for contributing to Pencil2D 😄 

I have no comments on the code really, it looks fine to me, so good job 👍 

I do however question whether there's a need to be able to change the zoom direction independently between the hand tool and the mouse wheel. I'd argue that if you want it on one tool, why not the other? While one can argue for the flexibility, we tend to strive to simplify in this project.

As such I think we can simplify the code by only having the zoom checkbox on the General Page.
<img width="289" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/05a9e45a-d4da-4a3b-8eb8-6d127a8f77c6">

2023-08-04 07:59 UTC, scribblemaniac commented
@MrStevns There may be a valid use case for keeping them separate. There is usually an operating system setting for natural scrolling, which will affect the direction of the mouse scroll wheel, but will not affect the hand tool. So depending on your system settings, you could for example end up with the mouse wheel working as you expect, and the hand tool not, and inverting both would just result in the hand tool working and the mouse wheel not. I don't think there's an obviously right way to match scroll wheel direction with mouse dragging direction, so maybe having an option for each would be best?

Also, I think it might be best to implement each setting as a combo box with "System" as the default, and two options for the two different directions (not sure what the best names for these would be). This way, when you set Pencil2D to use a specific behavior, it will continue to work that way regardless of changes to system settings.

2023-08-04 15:06 UTC, HeCorr commented
> There may be a valid use case for keeping them separate.

In my case specifically, I would definitely want the drag direction to be inverted but not the scroll wheel (so the behavior is similar to other software like Blender). I implemented both separately to give the user more flexible options  :)

> Also, I think it might be best to implement each setting as a combo box with "System" as the default, and two options for the two different directions (not sure what the best names for these would be). This way, when you set Pencil2D to use a specific behavior, it will continue to work that way regardless of changes to system settings.

I did consider a ComboBox with options instead of an "Invert" CheckBox, but since this is my first time contributing to a Qt-based project, I think that would have been more complicated to set up in comparison.

2023-08-04 15:08 UTC, HeCorr commented on core_lib/src/interface/scribblearea.cpp
> +        }
That's a very good point! I'll be doing that then since it will make the code cleaner.

2023-08-04 16:20 UTC, HeCorr commented on core_lib/src/interface/scribblearea.cpp
> +        }
I called both variables `mDeltaFactor` for consistency.

2023-08-05 08:09 UTC, MrStevns commented
> 

If they provide no such information, then it's just false, I don't see the problem with that? Or you mean that it could mean that it's possible to do on the OS but there's no way to fetch that information? In that case I agree it would be confusing

2023-08-06 11:25 UTC, MrStevns approved these changes
Given that some of the other team members voiced their reason about keeping both options as a toggle, with valid points, I have no further changes to the PR.

In order to avoid delaying the PR longer than necessary, I say we wait with the combo box discussion, until we can come to an agreement. Then we can always improve it later.

2023-08-06 11:34 UTC, merged

2023-08-06 11:35 UTC, MrStevns commented
Merged!, Thanks for being patient and for contributing to Pencil2D 🎉

2023-08-06 14:29 UTC, MrStevns commented
> Of course you could just accept that, on platforms that don’t provide the information, non-inverted essentially turns into a second “system” option and inverted turns into a “system inverted” option. But tbh I don’t quite see how such a tri-state preference provides enough added value to justify adding two options that aren’t even going to work as intended on (according to the documentation) “many platforms”.

Exactly, that is how I would have done it, though in hindsight I can see why that's not idea...

2023-08-07 06:31 UTC, scribblemaniac commented
I think we should do some testing to figure out what exactly "many platforms" means, and then go from there. I agree that there would be some undesirable behavior on platforms where this does not work, particularly depending on how each of the options is described.