Make OnionSkins UI more compact
pencil2d/pencil pull request #1824
Opened 2024-04-19 06:45 UTC by chchwy

Improve the OnionSkins UI by reducing the spacing between UI components.

Currently, on my HiDPI laptop displays (Win11 with 150% scaling), the OnionSkins options are barely visible. We can improve it by minimizing the spacing between UI elements, so more options can be displayed within the limited available space.

Please see the before/after screenshots as follows:

### Before
![onionskins-old](https://github.com/pencil2d/pencil/assets/163800/fb34a822-72e2-4871-9517-513ad9fbfa31)

### After
![onionskins-new](https://github.com/pencil2d/pencil/assets/163800/5f9cb824-009b-45d7-8954-6bc501ceff60)

2024-04-21 18:06 UTC, scribblemaniac requested changes
While I agree this change is an improvement on Windows, it doesn't look as good on Linux/GNOME. On the left is your version, the right is the old version (the font is slightly different in the AppImage apparently):
![Screenshot from 2024-04-21 11-52-59](https://github.com/pencil2d/pencil/assets/3461051/1540eab4-95ce-4a01-87b4-6c8811ff4b73)
Because the border is drawn underneath the group box text instead of through it, it looks to me like there isn't enough padding on the top. I think we should add 3px to the `LayoutTopMargin` of `nextFramesGroup` and `prevFramesGroup` so that it's evenly spaced on Linux. While OS specific code could be added, I don't think it's worth it for 6px.

2024-04-22 07:52 UTC, chchwy commented
> While I agree this change is an improvement on Windows, it doesn't look as good on Linux/GNOME. On the left is your version, the right is the old version (the font is slightly different in the AppImage apparently): ![Screenshot from 2024-04-21 11-52-59](https://private-user-images.githubusercontent.com/3461051/324268542-1540eab4-95ce-4a01-87b4-6c8811ff4b73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzI0MjksIm5iZiI6MTcxMzc3MjEyOSwicGF0aCI6Ii8zNDYxMDUxLzMyNDI2ODU0Mi0xNTQwZWFiNC05NWNlLTRhMDEtODdiNC02Yzg4MTFmZjRiNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMDc0ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzczNDkxZDJjNjJmNzQyMmFiN2JhOTg0NjExNjQwZmI1YjcwZWZmNWNiMWVlOGM2ZjNmOWE1YjgwMGU1ZTA5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gM9bRDLYDtK6_MOjiGtseW0s5yjpA-HHG2B-7OAs0es) Because the border is drawn underneath the group box text instead of through it, it looks to me like there isn't enough padding on the top. I think we should add 3px to the `LayoutTopMargin` of `nextFramesGroup` and `prevFramesGroup` so that it's evenly spaced on Linux. While OS specific code could be added, I don't think it's worth it for 6px.

thanks for testing. I will tweak the spacing to see if I can make it look better.

2024-04-22 07:58 UTC, chchwy commented
BTW, this not only improves the Windows app but also enhances the Mac app, which by default uses a HiDPI display

Original
<img width="1440" alt="old" src="https://github.com/pencil2d/pencil/assets/163800/a25dd9a0-7754-484b-9c06-dd5bc10b5959">

Compact
<img width="1440" alt="compact" src="https://github.com/pencil2d/pencil/assets/163800/025d1520-b823-435d-b85e-86cef8f6c876">

2024-04-25 04:12 UTC, scribblemaniac commented
Maybe we shouldn't use QGroupBox here if the display is so inconsistent and keeping the layout compact is a priority?

2024-04-26 09:15 UTC, chchwy commented
@J5lx @scribblemaniac I've adjusted the margins, could you please test it again?

2024-04-26 19:37 UTC, MrStevns commented
It's not quite there imo, the padding is off on macOS.
<img width="194" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/0a1db32d-4a20-4eaa-acde-333747fb6ae0">

I agree with Jacob that trying to sub-optimize this to shave off a few pixels is a bit silly, when we should instead consider either rethinking it or creating a custom UI that can be made smaller.

2024-04-27 02:47 UTC, chchwy commented
> It's not quite there imo, the padding is off on macOS. <img alt="image" width="194" src="https://private-user-images.githubusercontent.com/1045397/326094259-0a1db32d-4a20-4eaa-acde-333747fb6ae0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODYyMDMsIm5iZiI6MTcxNDE4NTkwMywicGF0aCI6Ii8xMDQ1Mzk3LzMyNjA5NDI1OS0wYTFkYjMyZC00YTIwLTRlYWEtYWNkZS0zMzM3NDdmYjZhZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDI0NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTI5NzM3NGY4MDI1MTQ5YzcwYjY5Mjg2ZjY5NTBlMDA3ODQ3NzlhOTU0NmQwODZkNGU3ZDkwYWFjYjAzOWE4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qv3OQtBptr_C_wKsd1bxI-dQY1UwZdxeobz5uQf5h7M">
> 
> I agree with Jacob that trying to sub-optimize this to shave off a few pixels is a bit silly, when we should instead consider either rethinking it or creating a custom UI that can be made smaller.
> 
> Spacing should be consistent between our widgets, anything else is a UI blunder if you ask me. <img alt="image" width="194" src="https://private-user-images.githubusercontent.com/1045397/326095165-3e822950-87f2-459a-8451-cbddceafee8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODYyMDMsIm5iZiI6MTcxNDE4NTkwMywicGF0aCI6Ii8xMDQ1Mzk3LzMyNjA5NTE2NS0zZTgyMjk1MC04N2YyLTQ1OWEtODQ1MS1jYmRkY2VhZmVlOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDI0NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U5M2E5NGE0NmU3ZDE5ZTJmM2I0NmMxM2M1ZTcyYWJjOTNhODNmZWE2NDVlNWFmMDhmOGRiNmM5OGViYzZlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o66gsl1-OwFCMEbWmVujMF7VxvFh9AkXlPj9ypSsLGA">
> 
> This, as it was, is better because it's aligned and there's space. Padding is important to make UI not feel cramped. <img alt="image" width="188" src="https://private-user-images.githubusercontent.com/1045397/326095468-b6e10bce-6f24-43d5-9272-b565f3bef3f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODYyMDMsIm5iZiI6MTcxNDE4NTkwMywicGF0aCI6Ii8xMDQ1Mzk3LzMyNjA5NTQ2OC1iNmUxMGJjZS02ZjI0LTQzZDUtOTI3Mi1iNTY1ZjNiZWYzZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDI0NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQyZGExNGE0YzVkOTNkMDZlYzEyYzQxYWI5ZGY0OTAwZjE3NzM0ZDIwOTAyZTE1N2Q2MjViOGI5NmIzMTZkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jfgMnqgDV3MKb62avc0fM9jGxTn9N_hAiStAjUX6fms">

2024-04-27 02:54 UTC, chchwy commented
> It's not quite there imo, the padding is off on macOS. <img alt="image" width="194" src="https://private-user-images.githubusercontent.com/1045397/326094259-0a1db32d-4a20-4eaa-acde-333747fb6ae0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODYyMDMsIm5iZiI6MTcxNDE4NTkwMywicGF0aCI6Ii8xMDQ1Mzk3LzMyNjA5NDI1OS0wYTFkYjMyZC00YTIwLTRlYWEtYWNkZS0zMzM3NDdmYjZhZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDI0NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTI5NzM3NGY4MDI1MTQ5YzcwYjY5Mjg2ZjY5NTBlMDA3ODQ3NzlhOTU0NmQwODZkNGU3ZDkwYWFjYjAzOWE4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qv3OQtBptr_C_wKsd1bxI-dQY1UwZdxeobz5uQf5h7M">

I don't see obvious problems in this screenshot. can you elaborate more? 

> 
> I agree with Jacob that trying to sub-optimize this to shave off a few pixels is a bit silly, when we should instead consider either rethinking it or creating a custom UI that can be made smaller.
> 
> Spacing should be consistent between our widgets, anything else is a UI blunder if you ask me. <img alt="image" width="194" src="https://private-user-images.githubusercontent.com/1045397/326095165-3e822950-87f2-459a-8451-cbddceafee8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODYyMDMsIm5iZiI6MTcxNDE4NTkwMywicGF0aCI6Ii8xMDQ1Mzk3LzMyNjA5NTE2NS0zZTgyMjk1MC04N2YyLTQ1OWEtODQ1MS1jYmRkY2VhZmVlOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDI0NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U5M2E5NGE0NmU3ZDE5ZTJmM2I0NmMxM2M1ZTcyYWJjOTNhODNmZWE2NDVlNWFmMDhmOGRiNmM5OGViYzZlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o66gsl1-OwFCMEbWmVujMF7VxvFh9AkXlPj9ypSsLGA">
> 
> This, as it was, is better because it's aligned and there's space. Padding is important to make UI not feel cramped. <img alt="image" width="188" src="https://private-user-images.githubusercontent.com/1045397/326095468-b6e10bce-6f24-43d5-9272-b565f3bef3f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODYyMDMsIm5iZiI6MTcxNDE4NTkwMywicGF0aCI6Ii8xMDQ1Mzk3LzMyNjA5NTQ2OC1iNmUxMGJjZS02ZjI0LTQzZDUtOTI3Mi1iNTY1ZjNiZWYzZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMDI0NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQyZGExNGE0YzVkOTNkMDZlYzEyYzQxYWI5ZGY0OTAwZjE3NzM0ZDIwOTAyZTE1N2Q2MjViOGI5NmIzMTZkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jfgMnqgDV3MKb62avc0fM9jGxTn9N_hAiStAjUX6fms">

May I ask what your screen size is and the resolutions? The discussion will go in the wrong direction if we only talk about aesthetic. The change here want to strike a balance between the aesthetic and usability with HiDPI display.

2024-04-27 03:02 UTC, chchwy commented
> > Maybe we shouldn't use QGroupBox here if the display is so inconsistent and keeping the layout compact is a priority?
> 
> I don’t think this is something we should even have to worry about. To be completely honest, I’m not entirely convinced of this micromanagement of spacing and margin values in the first place. This will shave off a few pixels now, but the moment we make more meaningful changes (like the addition of [an onion skin global toggle](/pencil2d/pencil/issues/1085)), we’ll be back to square one. If we’re really that concerned about keeping all the stuff on screen, we should just arrange (some of) the tool windows horizontally next to each other by default, rather than stacking them all vertically, or reduce the overall UI scale, or lock the tool windows by default in order to conserve the space consumed by their titlebars. I worry that if we instead choose to micromanage our pixels like this we’ll just end up dealing with more edge-cases like these groupboxes in the future.

I don't really agree that space reduction is micro-management. 

The things you mentioned above, the global onion toggle and horizontal tools options, they are all valuable and should be considered seriously. However, these thins do not conflict with the space reduction. 

If you look at other tools such as Photoshop, Paint Tool SAI or Procreate, you may notice that they are extremely reluctant to put spaces between UI components in order to make the most use of limited screen spaces.

I want to emphasize again that I want to improve the usability with HiDPI display as they are becoming more and more common the current UI usability with HiDPI display is quite poor.

2024-04-27 08:47 UTC, MrStevns commented
> May I ask what your screen size is and the resolutions? The discussion will go in the wrong direction if we only talk about aesthetic. The change here want to strike a balance between the aesthetic and usability with HiDPI display.

My resolution is technically (2560 × 1600) but I have scaled UI, so it appears to be 1440x900. The screen is 13 inches.

I understand that you want to strike a balance between aesthetic and usability, which is fine, as long as it's consistent across our widgets. For example if we should have 2 or 3 px instead of 6 px padding everywhere, then that's fine too, as long as it's consistent.

You can see the padding difference here:
![image](https://github.com/pencil2d/pencil/assets/1045397/d928d68f-56e6-4f6e-be07-2b9f509f52b0)

Looking at the code, the padding is 3 px around the overall group, yet there appears to be more spacing on the right side.
From a bit of digging, it seems to come from the checkboxes not being placed in a layout.

The interesting thing here is that if I tweak the spacing, the font size and try to squish the layout as much as possible, the layout still ends up being wider than your the changes you made, which just shows that tweaking this has all kinds of weird outcomes.

<img width="212" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/b2749f2d-9d00-48a8-9129-1ceeeafeeb56">

Top: My tweaked layout
Behind: Your tweaked layout

When I compare our layout with my CSP layout, ours is 25-30 px wider, but you can also see that they do all kinds of trickery to get it smaller, like squishing the size, potentially hiding it partially behind UI, having generally a more compact layout by more or less embedding the description into the slider component.

| CSP | Pencil2D (chchwy) | Pencil2D (MrStevns) |
| ---- | --------- | ------- |
| <img width="165" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/ef0d432e-77a4-473c-b07d-ce3af658c1a7"> | <img width="188" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/5b4a5c22-fdc5-4a38-bc2b-cbb4fb44f7c1"> | <img width="192" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/7edb34cc-8a6f-437b-9526-109e531dc5b6"> |
| 165 px | 188 px | 192 px |

What we can do is change the minimum component size too, which apparently is 192 px in my case. Changing this manually to, we could probably go down to 140 pixels and it would look alright, that's of course with the tweaked font size too. Would that be sufficient?

| 11 point font size | 13 point font size | 
| ----------------- | ----------------- | 
<img width="142" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/e07934cb-6a7a-4b26-9ed5-9a6b4ed541f6"> | <img width="162" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/87f7f8cf-d836-4bef-9df9-eeb52fa1b6ab">
| 142 px | 162 |

2024-04-27 11:04 UTC, chchwy commented
Thanks a lot for the efforts. I was thinking of starting small from a single widget and then step by step making the changes to other widgets. But you have done them all! That's fantastic. I will definitely check your branch out when I get time.

2024-04-27 11:05 UTC, chchwy commented
BTW, I also thinking of replacing the title bar of dock widgets. The default title bars eat a lot of spaces.

2024-04-27 11:13 UTC, MrStevns commented
I agree, changing the titlebar widgets or getting rid of them entirely in docked mode is also something I've experimented with during my early timeline mockups. Integrating the close and popup button directly into the given widget would make the UI a lot more compact vertically, on mac os at least.

this is a mockup from 2020, so the style does not fit anymore but the concept itself could probably still be applied.
<img width="948" alt="image" src="https://github.com/pencil2d/pencil/assets/1045397/5b5e47ec-9f90-4954-bbe2-12e88d455dea">

2024-04-29 08:21 UTC, closed without merging