Improve preferences layout for long translations
pencil2d/pencil pull request #1856
Opened 2024-06-29 17:11 UTC by J5lx

Fixes #1850 by simply removing the size restriction altogether. I couldn’t think of a good reason to keep it. I also made the dialog a little bigger by default and made some changes to the “tab bar” to avoid cutting off long translations.

Before:

![image](https://github.com/pencil2d/pencil/assets/2063777/511511c2-b02d-4e1f-a0a2-44833894951e)

After:

![image](https://github.com/pencil2d/pencil/assets/2063777/7d578da2-cc0c-42b9-9019-36ef87ae51c5)

2024-06-29 17:34 UTC, MrStevns requested changes
The removal of the size constraint on the dialog is fine by me, not sure why we had it either.

The code you added to improve on the tab view placing completely broke it for me though. 

![loooong](https://github.com/pencil2d/pencil/assets/1045397/77d2c238-0f1c-4324-9e04-8c9f2413e02a)

2024-06-29 19:11 UTC, MrStevns commented
> That’s odd, I’m definitely not seeing that on Linux. On Windows, Qt 5 has that issue but not Qt 6, maybe that’s the issue? I’ll see if I can figure out what’s going on there.

Ah good point, I was testing with Qt 5 but even with my Qt 6 build the issue remains. I've tested with 6.6.2 and 6.7.0.

2024-06-30 07:16 UTC, MrStevns approved these changes
That did the trick, both qt 5 and qt 6 works now, as such I think we can approve of these changes.

2024-06-30 07:18 UTC, MrStevns commented
btw. shouldn't the PR point to the release branch or are we simply not applying more bug fixes to the release?

2024-06-30 08:29 UTC, chchwy commented
> btw. shouldn't the PR point to the release branch or are we simply not applying more bug fixes to the release?

Target the master branch since the change was made based on the master branch. And then I will cherry-pick this to the release branch later on.

2024-06-30 08:36 UTC, chchwy approved these changes

2024-07-02 05:27 UTC, merged